### ISSUE TITLE
land surface as feature type

### ISSUE THREAD

**Issue by meganrwong** [ANZSoilData/def-au-asls-land-surface#1]
http://anzsoil.org/def/au/asls/land-surface

We were using this as a feature type  , and enquired re possibility of being encoded so 

However we can now use http://purl.obolibrary.org/obo/ENVO_01001785

which is specialization of ‘astronomical body’ that was requested, see - 

[#1249] Add synonym 'land surface' to 'surface of an astronomical body' by dr-shorthair · Pull Request #1254 · EnvironmentOntology/envo 

Just put here for your noting for encoding revisions

**Comment by dr-shorthair** [comment]
I guess when you use it that way then you can 'infer' that 
```
http://anzsoil.org/def/au/asls/land-surface a geo:Feature or ext:FeatureType . 
```
It does not need to be explicitly stated in the vocab through - the absence of this axiom does not prevent you referring to it in that way.

**Comment by meganrwong** [comment]
Nothing to resolve. Close. Was just a comment noting the use of an equivalent ENVO term to ansls land surface FeatureType in VAS/soil CRC work.
